### PR TITLE
Pycache added to .gitignore

### PR DESCRIPTION
**Pull request by niiita**
## __pycache__ added to .gitignore

edited gitignore so that pychache files would not be commited

### CODE REVIEW

**Comment by alvyn279** [comment]
Good thought for ignoring the compiled .py files in pycache, as the latter is useless on remote branch

**Comment by Lercerss** [comment]
What is happening here with the commits? It seems like this branch contains more than just the change to `.gitignore`. I think we should fix this before merging the branch. Otherwise the change in 97c4a4c1f90e44caad28793208f75b7619cbac26 is a good idea.

You could try to clean up your branch by removing the unnecessary commits, though that can sometimes be a difficult operation. You could also start a new branch off master and use `git cherry-pick <commit>` to reapply specific commits, where `<commit>` is the first 6-7 characters in the commit's hash, i.e. in your case probably "97c4a4c". 

Another issue I can see is that, as of writing this comment, this branch would conflict with master since it does not contain the addition of "venv" to `.gitignore`. You can watch out for this in the future this by making sure to use before opening a pull request
```
git fetch
git rebase origin/master
```
and fixing any merge conflicts that arise.

**Comment by alvyn279** [comment]
Hanna, I think you should make a commit in branch **init_django_project** by editing the .gitignore file there for pycache ignoring.

**Comment by Lercerss** [comment]
That's not a bad idea, this way we can drop this PR altogether and just focus on #16.

**Comment by alvyn279** [comment]
Exactly

**Pull request closed without merging**
